- name: Config VM
  hosts: vm
  become: true
  gather_facts: false
  roles:
    - docker

- name: Configurer le seveur
  hosts: webservers
  become: true
  gather_facts: false
  roles:
    - nginx_basique

- name: Configurer SQL
  hosts: db
  become: true
  gather_facts: false
  roles:
    - mysql