FROM debian:bullseye

RUN apt-get update -y \
&& apt-get upgrade -y \
&& apt-get install openssl nginx php-fpm -y

RUN mkdir -p /etc/nginx/ssl \
&& openssl req -x509 -nodes -out /etc/nginx/ssl/inception.crt \
-keyout /etc/nginx/ssl/inception.key -subj "/CN=inception"

COPY ./conf/nginx.conf ./etc/nginx/
RUN mkdir -p /home/anvincen/data/ && chown -R www-data:www-data /home/anvincen/data

EXPOSE 443

COPY ./tools/nginx-init.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/nginx-init.sh

ENTRYPOINT ["/usr/local/bin/nginx-init.sh"]