- name : Check apt
  ansible.builtin.apt:
    name:
      - python3-apt
      - aptitude

- name: Installer Docker et le plugin compose
  ansible.builtin.apt:
      name:
        - ca-certificates
        - curl
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
      state: present
      update_cache: true
      auto_install_module_deps: true

- name: Assurer que docker tourne
  ansible.builtin.systemd:
      name: docker
      state: started
      enabled: true

- name: Creer le reseau
  community.docker.docker_network:
    name: app_net
    # connected: []
    # certif